# Generated by Django 5.0.6 on 2024-06-25 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
