# Generated by Django 5.0.6 on 2024-06-25 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
    ]
