# Generated by Django 5.0.6 on 2024-06-25 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8635d993-248b-476d-87f6-3c995577ab5e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8635d993-248b-476d-87f6-3c995577ab5e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8635d993-248b-476d-87f6-3c995577ab5e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8635d993-248b-476d-87f6-3c995577ab5e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
