# Generated by Django 5.0.6 on 2024-06-25 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4765f21a-9045-4dee-b099-b79e5ad51ae0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
