# Generated by Django 5.0.6 on 2024-06-25 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_commentlike_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98025916-ee8d-48ef-bd41-f55772653b93'), editable=False, primary_key=True, serialize=False),
        ),
    ]
